FROM postgres:11-alpine
LABEL maintainer="ryo_m_code <ryo.m.code@gmail.com>"

ENV TZ=UTC \
  POSTGRES_DB=september_db \
  POSTGRES_USER=admin \
  POSTGRES_PASSWORD=admin

#設定が必要になったら追記
#COPY ./infra/docker/postgres/pg.cnf /etc/pg.cnf
